adding examples
luizalabs/dev.magalu.com-docs pull request #5
Opened 2021-07-30 20:30 UTC by felipexy

2021-08-02 19:56 UTC, sp0oks commented
Acho que é uma boa você colocar uma descrição do seu PR, objetivos e etc pra gente poder dar uma revisada melhor, o que você acha?

2021-08-02 20:05 UTC, felipexy commented
> Acho que é uma boa você colocar uma descrição do seu PR, objetivos e etc pra gente poder dar uma revisada melhor, o que você acha?

Claro, perdão!

2021-08-02 21:32 UTC, kikoreis commented
Alguns comentários:

- Vamos usar nomes minúsculos para os diretórios, pode ser?
- Seria melhor batizar sua app demo com um nome mais específico do que "Code". Me fala um pouco mais, o que a app faz?
- Faz sentido as collections estarem em examples?

2021-08-03 17:15 UTC, felipexy commented
> Alguns comentários:
> 
>     * Vamos usar nomes minúsculos para os diretórios, pode ser?
> 
>     * Seria melhor batizar sua app demo com um nome mais específico do que "Code". Me fala um pouco mais, o que a app faz?
> 
>     * Faz sentido as collections estarem em examples?

Fala Kiko!

Sobre as observações:
* Alterei os nomes de diretórios para o padrão de inicial minúscula.
* O nome da pasta que contém o App-Demo agora se chama "demoApp_check_orders".
* Criei uma pasta "collections" no root para separar dos exemplos de código.

2021-08-04 18:11 UTC, kikoreis requested changes
Obrigado pelo patch! Fiz dois comentários pequenos e mais três coisas:

1. Esse collection do postman é gerado automaticamente no build process do Maestro?
2. Em geral não queremos o caractere espaço em um pathname, e acho que deveria ser minúsculas. Talvez só "collections/maestro.json", com o padrão sendo a string do nome do produto?
3. Vamos chamar o app de check_orders então? Tira o "demoApp_" da frente do diretório, porque o examples é exatamente para isso.

2021-08-04 18:11 UTC, kikoreis commented on examples/demoApp_check_orders/.env.example
> +REACT_APP_API_ENDPOINT_KEYCLOACK_AUTH=https://id.magalu.com/auth/realms/master/protocol/openid-connect/auth?client_id=
Esses endpoints não mudaram?

2021-08-04 18:11 UTC, kikoreis commented on examples/demoApp_check_orders/.env.example
> +REACT_APP_API_ENDPOINT_GET_SPECIFIC_ORDER=https://alpha.api.magalu.com/maestro/v1/orders?number=
Acho que tudo bem sair alpha agora mas tem que lembrar que vai ter que rolar um patch para tirar o alpha depois.

2021-08-04 18:53 UTC, felipexy commented on examples/demoApp_check_orders/.env.example
> +REACT_APP_API_ENDPOINT_KEYCLOACK_AUTH=https://id.magalu.com/auth/realms/master/protocol/openid-connect/auth?client_id=
Até onde sei, não

2021-08-04 18:53 UTC, felipexy commented on examples/demoApp_check_orders/.env.example
> +REACT_APP_API_ENDPOINT_GET_SPECIFIC_ORDER=https://alpha.api.magalu.com/maestro/v1/orders?number=
Sim, sem dúvidas!

2021-08-10 14:35 UTC, alcidesmig commented on examples/check_orders/README.md
> +git clone git@gitlab.luizalabs.com:wesley.bonini/appdemo.git
Opa, acho que aqui precisa ser atualizado.

2021-08-10 17:59 UTC, fczuardi-luizalabs reviewed
Vou deixar uns comentários sobre o código nas linhas do patch, mas queria levantar uma discussão mais genérica quanto ao projeto todo e sobre se deveriamos usar um só repositorio para acumular todo tipo de exemplos.

Como está, esta app demo é uma web app completa, que poderia ser um projeto open source com repositorio prório. Ela possui detalhes nao diretamente relacionados a um exemplo de uso da API. Por exemplo, tem implementacao de um componente de UI accordion, várias dependencias como redux, matterial-ui, moment, react-router, etc... É um exemplo grande, completo, que poderia existir sozinha num repo e estar linkada num showcase de cases ou projetos abertos espalhados por ai.

Meu ponto é o de que muito do que nao é o exemplo de consumo das APIs pode ser ruído numa pasta examples de um projeto cujo nome é "dev.magalu.com-docs". Mas enfim, este proprio repositório IMHO está com crise de identidade, queremos mesmo centralizar guias, collections de postman e projetos open source tudo num repo só?

2021-08-10 17:59 UTC, fczuardi-luizalabs commented on examples/check_orders/.env.example
> +REACT_APP_API_ENDPOINT_KEYCLOACK_AUTH=https://id.magalu.com/auth/realms/master/protocol/openid-connect/auth?client_id=
Nossa authenticacao é OAuth2, acho que é irrelevante o fato de usarmos Keycloak e isso poderia ficar de fora do nome da variável, até pq amanha ou depois o software do nosso identity provider / oidc authority pode ser outro (por exemplo, Okta).

E agora temos URLs mais simples para estes endpoints, vale a pena usarmos estas aqui:

https://id.magalu.com/oauth/auth
https://id.magalu.com/oauth/token
https://id.magalu.com/oauth/token/introspect
https://id.magalu.com/oauth/userinfo
https://id.magalu.com/oauth/logout
https://id.magalu.com/oauth/certs

2021-08-10 17:59 UTC, fczuardi-luizalabs commented on examples/check_orders/.env.example
> +REACT_APP_API_ENDPOINT_HOME=http://localhost:3000
minhas sugestões:

```
REACT_APP_CLIENT_ID=
REACT_APP_CLIENT_SECRET=
REACT_APP_URI=http://localhost:3000
REACT_APP_OIDC_AUTH_URI=https://id.magalu.com/oauth/auth
REACT_APP_OIDC_TOKEN_URI=https://id.magalu.com/oauth/token
REACT_APP_OMS_API_URI=https://alpha.api.magalu.com/maestro/v1
```

E deixar a parte que vem depois do `/maestro/v1` la para dentro do código.

2021-08-10 17:59 UTC, fczuardi-luizalabs commented on examples/check_orders/README.md
> +## O App demo para acesso às API de Order da Magalu
Sei la, achei um pouco pretencioso "O App" e o fato de ter um nome estilo marca (DemOrders), creio que a ideia é termos muitos exemplos de uso das apis, vários códigos de referencia para cada coisa, em multiplas tecnologias e linguagens, entao chamar de "O" como "o um anel" não deixa claro que este é "um" de muitos.

```suggestion
## Exemplo de aplicativo web que utiliza login OAuth2 e consome a API de pedidos Maestro da Plataforma Aberta Magalu
```

2021-08-10 17:59 UTC, fczuardi-luizalabs commented on examples/check_orders/README.md
> +Este projeto é Open Source com um repositório público.
Acho que vale incluir um arquivo LICENSE então, a recomendação mais simples aqui seria MIT.

2021-08-10 18:26 UTC, fczuardi-luizalabs reviewed
mais alguns comentarios, vendo este tanto de arquivos que vieram do boilerplate, reforço minha recomendacao de que esta web application seja um repo open source separado

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/README.md
> +git clone git@gitlab.luizalabs.com:wesley.bonini/appdemo.git
trocar pela URL final do repositorio git

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/package.json
> +    "web-vitals": "^1.0.1"
acho que vale uma faxina para limpar daqui dependencias que nao estiverem sendo usadas

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/README.md
> +
acho que vale mencionar o boilerplate usado, foi create-react-app? deixe um link

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/components/components/Accordion/Accordion.js
> +  const somaCompras = (packages) => {
está destoando um pouco este nome em Portugues aqui

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/components/pages/Login/index.js
> +        await getJWT(codeResponse).catch(error => {
o axios request de dentro da funcao getJWT tem um catch, a chamada dela tem este catch aqui e está dentro de um try com catch... faz sentido ter 3 catches?

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/services/get.orders.jsx
> +      "x-tenant-id": decodedJWT.customer.uuid,
é assim mesmo que vem o tenant id dentro do token?

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/services/get.orders.jsx
> +      localStorage.setItem("order", JSON.stringify(response.data));
ta um pouco confuso este side-effect aqui, a funcao chama getOrders e ela escreve no localStorage? será que para fins de claridade nao é melhor só retornar a Promise e deixa quem chamou tratar o que quer fazer com a resposta?

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/services/get.orders.jsx
> +      localStorage.setItem("order", JSON.stringify(response.data));
idem, uma funcao que chama get está fazendo um set

2021-08-10 18:26 UTC, fczuardi-luizalabs commented on examples/check_orders/src/services/post.jwt.jsx
> +      localStorage.setItem("jwt", response.data.access_token);
mesmo anti-pattern, talvez refatorar para retornar a promise

2021-08-11 20:53 UTC, fczuardi-luizalabs commented on examples/check_orders/README.md
> +Este projeto é Open Source com um repositório público.
resolvido

2021-08-11 21:00 UTC, felipexy commented on examples/check_orders/src/services/get.orders.jsx
> +      localStorage.setItem("order", JSON.stringify(response.data));
Vamos tratar numa follow up issue

2021-08-12 12:21 UTC, merged